site_name: fusrr Documentation
site_description: fusrr, a Python package for rendering and visualizing fusion reactor CAD models and generating images and videos of them.
site_url: https://idk.com/
repo_name: Fusion-Power-Plant-Framework/fusrr
repo_url: https://github.com/Fusion-Power-Plant-Framework/fusrr
theme:
  name: material
watch:
  - fusrr
plugins:
  - mkdocstrings
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - autorefs
nav:
  - index.md
  - examples.md
  - Code Reference:
      - pipeline.py: reference/fusrr.base.pipeline.md
