[tool.poetry]
name = "fusrr-pipeline"
version = "0.1.0"
description = ""
authors = ["The FusRR Pipeline project maintainers"]
readme = "README.md"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
]
packages = [{ include = "fusrr" }]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "3.10.*"
bpy = "^3.6.0"
numpy = "1.25.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
ruff = "^0.0.292"
pytest = "^7.4.2"
pytest-metadata = "^3.0.0"
pytest-html = "^4.0.2"
pytest-json-report = "^1.5.0"
ipython = "^8.16.1"
pre-commit = "^3.4.0"
