[build-system]
requires      = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source           = "vcs"
fallback-version = "0.0.0"

[tool.hatch.build.hooks.vcs]
version-file = "fusrr/_version.py"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "fusrr"
authors = [{ name = "The FusRR project maintainers" }]
description = ""
readme = "README.md"
dynamic = ['version']
license = "MIT"
requires-python = ">=3.13"
keywords = ["tokamak", "blender", "rendering", "nuclear", "fusion"]
classifiers = [
  "Programming Language :: Python",
  "Development Status :: 3 - Alpha",
  "Natural Language :: English",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "bpy", "numpy", "pydantic>=2.11.0"
  ]

[project.optional-dependencies]
dev = ["pre-commit", "jupyterlab"]
test = [
  "pytest",
  "coverage[toml]",
  "pytest-html",
  "pytest-metadata",
  "pytest-json-report",
]
docs = ["mkdocs-material", "mkdocstrings[python]"]
lint = ["ruff", "mypy"]
process = ["process @ git+https://github.com/ukaea/process@v3.3.0"]

[project.urls]
Source        = "https://github.com/Fusion-Power-Plant-Framework/fusrr"
Documentation = "https://github.com/Fusion-Power-Plant-Framework/fusrr#readme"
Issues        = "https://github.com/Fusion-Power-Plant-Framework/fusrr/issues"

# env: default
[tool.hatch.envs.default]
python = "3.13"
features = ["dev", "test", "lint"]

[tool.hatch.envs.docker-examples]
dependencies = ["process @ file:///PROCESS"]
[[tool.hatch.envs.docker-examples.matrix]]
python = ["3.13.0", "3.13.1", "3.13.2", "3.13.3", "3.13.4", "3.13.5", "3.13.6", "3.13.7", "3.13.8", "3.13.9", "3.13.10", "3.13.11", "3.13.12"]
[tool.hatch.envs.docker-examples.scripts]
# super hacky for now
run = "python examples/simple_scene.py && python examples/combined_eudemo/run_project.py"

# env: test
[tool.hatch.envs.test]
features = ["test"]
# when in Docker, it can only run tests on imported python versions, so must match
[[tool.hatch.envs.test.matrix]]
python = ["3.13.0", "3.13.1", "3.13.2", "3.13.3", "3.13.4", "3.13.5", "3.13.6", "3.13.7", "3.13.8", "3.13.9", "3.13.10", "3.13.11", "3.13.12"]
[tool.hatch.envs.test.scripts]
tests      = "pytest {args:tests}"
tests-cov  = "coverage run -m pytest {args:tests}"
cov-report = ["- coverage combine", "coverage report"]
cov-all    = ["tests-cov", "cov-report"]

# env: docs
[tool.hatch.envs.docs]
features = ["docs"]
[tool.hatch.envs.docs.scripts]
build = "mkdocs build"
serve = "mkdocs serve"

# env: lint
[tool.hatch.envs.lint]
detached     = true                   # Don't inherit from default (does not download project dependencies)
dependencies = ["ruff", "pre-commit"]
[tool.hatch.envs.lint.scripts]
style = "ruff check {args:.}"
fmt   = "pre-commit run --all-files --hook-stage manual"

# tool: ruff
[tool.ruff]
line-length = 80

exclude = [
  ".git",
  "__pycache__",
  "documentation",
  ".env",
  ".idea",
  ".pytest_cache",
  "htmlcov",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "UP047",  # likewise, fix soon
  "INP001", # Ignore requiring __init__.py files
  "D105",   # Don't require docstrings for magic methods
  "N802",   # Upper case function names are allowed
  "ANN002",
  "ANN003",
  "ERA001",
  "I001",
  "D100",
  "COM812",
  "ISC001",
  "D104",
  "D205",
  "ANN206",
  "ANN201",
  "ANN204",
  "T201",
  "N803",
  "N806",
  "N815",
  "TRY003",
  "EM101",
  "EM102",
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105",
  "S106",
  "S107",
  # Ignore complexity
  "C901",
  "PLR0911",
  "PLR0912",
  "PLR0913",
  "PLR0915",
  "FIX002",
  "TD002",
  "TD003",


  # should reenable these
  "D101",
  "D102",
  "D107",
  "ANN001",
  # "PLR2004 ", # Magic values

]
unfixable = [
  # Don't touch unused imports
  "F401",
]


[tool.ruff.lint.isort]
known-first-party = ["fusrr"]
force-to-top      = ["numpy", "bpy"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.mccabe]
max-complexity = 20

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*"  = ["PLR2004", "S101", "TID252", "D103"]
"__init__.py" = ["F401", "F403"]

[tool.coverage.run]
source_pkgs = ["fusrr", "tests"]
branch      = true
parallel    = true
omit        = ["fusrr/_version.py"]

[tool.coverage.paths]
fusrr = ["fusrr", "*/fusrr"]
tests = ["tests", "*/fusrr/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
"omit"        = ["fusrr/_version.py"]
