"""test for python_entry"""
import os
from pathlib import Path

from python_entry import imagepathname, save_image

delete_png = Path.cwd().glob(
    "*.png"
)  # will delete all pngs in cwd to ensure it is checking for the one generated by Python_entry
for path in delete_png:
    delete_png = path
    os.remove(delete_png)


def test_save_image():
    """Test to assert if render has been saved"""
    save_image(imagepathname)
    assert Path(imagepathname).exists()
