# Some variables are repeated to count inboard and outboard side
# dr_tf_shld_gap, rminor and dr_shld_blkt_gap
RADIAL_BUILD = [
    "dr_bore",
    "dr_cs",
    "dr_cs_precomp",
    "dr_cs_tf_gap",
    "dr_tf_inboard",
    "dr_tf_shld_gap",
    "dr_shld_thermal_inboard",
    "dr_shld_vv_gap_inboard",
    "dr_vv_inboard",
    "dr_shld_inboard",
    "dr_shld_blkt_gap",
    "dr_blkt_inboard",
    "dr_fw_inboard",
    "dr_fw_plasma_gap_inboard",
    "rminor",
    "rminor",
    "dr_fw_plasma_gap_outboard",
    "dr_fw_outboard",
    "dr_blkt_outboard",
    "dr_shld_blkt_gap",
    "dr_shld_outboard",
    "dr_vv_outboard",
    "dr_shld_vv_gap",
    "dr_shld_thermal_outboard",
    "dr_tf_shld_gap",
    "dr_tf_outboard",
]

vertical_upper = [
    "rminor*kappa",
    "dz_fw_plasma_gap",
    "dz_fw_upper",
    "dz_blkt_upper",
    "dr_shld_blkt_gap",
    "dz_shld_upper",
    "dz_vv_upper",
    "dz_shld_vv_gap",
    "dz_shld_thermal",
    "dr_tf_shld_gap",
    "dr_tf_inboard",
]

vertical_lower = [
    "rminor*kappa",
    "dz_xpoint_divertor",
    "dz_divertor",
    "dz_shld_lower",
    "dz_vv_lower",
    "dz_shld_vv_gap",
    "dz_shld_thermal",
    "dr_tf_shld_gap",
    "dr_tf_inboard",
]
