"""Dictionary for generic params for adaptor"""
# structure is key=renderingpipeline name
# value= external program name
process_param = {
    "rmajor": "rmajor",
    "n_tf": "n_tf",
    "rminor": "rminor",
    "delta_95": "triang95",
    "kappa95": "kappa95",
    "i_single_null": "i_single_null",
    # TF Coil use
    "x1": "xarc(1)",
    "x2": "xarc(2)",
    "x3": "xarc(3)",
    "x4": "xarc(4)",
    "x5": "xarc(5)",
    "y1": "yarc(1)",
    "y2": "yarc(2)",
    "y3": "yarc(3)",
    "y4": "yarc(4)",
    "y5": "yarc(5)",
    "tfc_inleg": "tfcth",
    "d_vv_in": "d_vv_in",
    "d_vv_out": "d_vv_out",
    "blnktth": "blnktth",
    "tftort": "tftort",
    # Blanket use
    "bore": "bore",
    "cs_rad_th": "ohcth",
    "precomp": "precomp",
    "cs_rad_gap": "gapoh",
    "tftsgap": "tftsgap",
    "thshield_ib": "thshield_ib",
    "thshldgap": "gapds",
    "shldith": "shldith",
    "vvblgapi": "vvblgapi",
    "blnkith": "blnkith",
    "fwith": "fwith",
    "scrapthi": "scrapli",
    "rminori": "rminor",
    "rminoro": "rminoro",
    "scraptho": "scraplo",
    "fwoth": "fwoth",
    "blnkoth": "blnkoth",
    "vvblgapo": "vvblgapo",
    "shldoth": "shldoth",
    "vvtfgap": "gapsto",
    "thshield_ob": "thshield_ob",
    "tfth_outleg": "tfthko",
    "rminor_kappa": "rminor*kappa",
    "vgaptop": "vgaptop",
    "fwtth": "fwtth",
    "vvblgap": "vvblgap",
    "shldtth": "shldtth",
    "d_vv_top": "d_vv_top",
    "vgap2": "vgap2",
    "thshield_vb": "thshield_vb",
    "vgap": "vgap",
    "divfix": "divfix",
    "shldlth": "shldlth",
    "d_vv_bot": "d_vv_bot",
    "tftsgap": "tftsgap",
    "triang": "triang",
    # PF coil use
    "ohdz": "ohdz",
    "iohcl": "iohcl",
    "rpf1": "rpf(01)",
    "rpf2": "rpf(02)",
    "rpf3": "rpf(03)",
    "rpf4": "rpf(04)",
    "rpf5": "rpf(05)",
    "rpf6": "rpf(06)",
    "zpf1": "zpf(01)",
    "zpf2": "zpf(02)",
    "zpf3": "zpf(03)",
    "zpf4": "zpf(04)",
    "zpf5": "zpf(05)",
    "zpf6": "zpf(06)",
    "pfdr1": "pfdr01",
    "pfdr2": "pfdr02",
    "pfdr3": "pfdr03",
    "pfdr4": "pfdr04",
    "pfdr5": "pfdr05",
    "pfdr6": "pfdr06",
    "pfdz1": "pfdz01",
    "pfdz2": "pfdz02",
    "pfdz3": "pfdz03",
    "pfdz4": "pfdz04",
    "pfdz5": "pfdz05",
    "pfdz6": "pfdz06",
    "rdewex": "rdewex",
    "ddwex": "ddwex",
    "zdewex": "zdewex",
}

"""
From plot_proc.py. Build tools
"""
RADIAL_BUILD = [
    "bore",
    "cs_rad_th",
    "precomp",
    "cs_rad_gap",
    "tfc_inleg",
    "tftsgap",
    "thshield_ib",
    "thshldgap",
    "d_vv_in",
    "shldith",
    "vvblgapi",
    "blnkith",
    "fwith",
    "scrapthi",
    "rminori",
    "rminoro",
    "scraptho",
    "fwoth",
    "blnkoth",
    "vvblgapo",
    "shldoth",
    "d_vv_out",
    "vvtfgap",
    "thshield_ob",
    "tftsgap",
    "tfth_outleg",
]

vertical_upper = [
    "rminor_kappa",
    "vgaptop",
    "fwtth",
    "blnktth",
    "vvblgap",
    "shldtth",
    "d_vv_top",
    "vgap2",
    "thshield_vb",
    "tftsgap",
    "tfc_inleg",
]

vertical_lower = [
    "rminor_kappa",
    "vgap",
    "divfix",
    "shldlth",
    "d_vv_bot",
    "vgap2",
    "thshield_vb",
    "tftsgap",
    "tfc_inleg",
]


bluemira_param = {
    "rmajor": "R_0",
    "No_TF": "n_TF",
    "delta95": "delta_95",
    "kappa95": "kappa95",
}
