services:
  fusrr:
    image: fusrr:latest
    container_name: fusrr-v0.1
    build:
      context: .
      dockerfile: Dockerfile
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: "no"
