"""Dictionary for generic params for adaptor"""
# structure is key=renderingpipeline name
# value= external program name
process_param = {
    "rmajor": "rmajor",
    "n_tf": "n_tf",
    "rminor": "rminor",
    "delta_95": "triang95",
    "kappa95": "kappa95",
    "i_single_null": "i_single_null",
    # TF Coil use
    "x1": "xarc(1)",
    "x2": "xarc(2)",
    "x3": "xarc(3)",
    "x4": "xarc(4)",
    "x5": "xarc(5)",
    "y1": "yarc(1)",
    "y2": "yarc(2)",
    "y3": "yarc(3)",
    "y4": "yarc(4)",
    "y5": "yarc(5)",
    "tfc_inleg": "tfcth",
    "d_vv_in": "d_vv_in",
    "d_vv_out": "d_vv_out",
    "blnktth": "blnktth",
    "tftort": "tftort",
    "casthi": "casthi",
    # Blanket use
    "bore": "bore",
    "cs_rad_th": "ohcth",
    "precomp": "precomp",
    "cs_rad_gap": "gapoh",
    "tftsgap": "tftsgap",
    "thshield_ib": "thshield_ib",
    "thshldgap": "gapds",
    "shldith": "shldith",
    "vvblgapi": "vvblgapi",
    "blnkith": "blnkith",
    "fwith": "fwith",
    "scrapthi": "scrapli",
    "rminori": "rminor",
    "rminoro": "rminoro",
    "scraptho": "scraplo",
    "fwoth": "fwoth",
    "blnkoth": "blnkoth",
    "vvblgapo": "vvblgapo",
    "shldoth": "shldoth",
    "vvtfgap": "gapsto",
    "thshield_ob": "thshield_ob",
    "tfth_outleg": "tfthko",
    "rminor_kappa": "rminor*kappa",
    "vgaptop": "vgaptop",
    "fwtth": "fwtth",
    "vvblgap": "vvblgap",
    "shldtth": "shldtth",
    "d_vv_top": "d_vv_top",
    "vgap2": "vgap2",
    "thshield_vb": "thshield_vb",
    "vgap": "vgap",
    "divfix": "divfix",
    "shldlth": "shldlth",
    "d_vv_bot": "d_vv_bot",
    "triang": "triang",
    # PF coil use
    "ohdz": "ohdz",
    "iohcl": "iohcl",
    "rpf1": "rpf[0]",
    "rpf2": "rpf[1]",
    "rpf3": "rpf[2]",
    "rpf4": "rpf[3]",
    "rpf5": "rpf[4]",
    "rpf6": "rpf[5]",
    "zpf1": "zpf[0]",
    "zpf2": "zpf[1]",
    "zpf3": "zpf[2]",
    "zpf4": "zpf[3]",
    "zpf5": "zpf[4]",
    "zpf6": "zpf[5]",
    "pfdr1": "pfdr(0)",
    "pfdr2": "pfdr(1)",
    "pfdr3": "pfdr(2)",
    "pfdr4": "pfdr(3)",
    "pfdr5": "pfdr(4)",
    "pfdr6": "pfdr(5)",
    "pfdz1": "pfdz(0)",
    "pfdz2": "pfdz(1)",
    "pfdz3": "pfdz(2)",
    "pfdz4": "pfdz(3)",
    "pfdz5": "pfdz(4)",
    "pfdz6": "pfdz(5)",
    "rdewex": "rdewex",
    "ddwex": "ddwex",
    "zdewex": "zdewex",
    "tfcth": "tfcth",
    # "ohcth": "cs_rad_th",
    "ohcth": "ohcth",
    "gapoh": "gapoh",
    "gapds": "gapds",
    "scrapli": "scrapli",
    "scraplo": "scraplo",
}

"""
From plot_proc.py. Build tools
"""
RADIAL_BUILD = [
    "bore",
    "ohcth",
    "precomp",
    "gapoh",
    "tfcth",
    "tftsgap",
    "thshield_ib",
    "gapds",
    "d_vv_in",
    "shldith",
    "vvblgapi",
    "blnkith",
    "fwith",
    "scrapli",
    "rminori",
    "rminoro",
    "scraplo",
    "fwoth",
    "blnkoth",
    "vvblgapo",
    "shldoth",
    "d_vv_out",
    "gapsto",
    "thshield_ob",
    "tftsgap",
    "tfthko",
]

vertical_upper = [
    "rminor_kappa",
    "vgaptop",
    "fwtth",
    "blnktth",
    "vvblgap",
    "shldtth",
    "d_vv_top",
    "vgap2",
    "thshield_vb",
    "tftsgap",
    "tfcth",
]

vertical_lower = [
    "rminor_kappa",
    "vgap",
    "divfix",
    "shldlth",
    "d_vv_bot",
    "vgap2",
    "thshield_vb",
    "tftsgap",
    "tfcth",
]


bluemira_param = {
    "rmajor": "R_0",
    "No_TF": "n_TF",
    "delta95": "delta_95",
    "kappa95": "kappa95",
}
