name: Push FusRR Docker Image to GHCR
description: Push the FusRR Docker Image with latest and commit sha tags to GitHub Container Registry

inputs:
  image_name_latest:
    description: "The name of the Docker image with the :latest tag"
    required: true
  image_name_sha:
    description: "The name of the Docker image with the :commit_sha tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile
        push: true
        tags: ${{ inputs.image_name }}:latest, ${{ inputs.image_name }}:${{ github.sha }}
