name: Build FusRR Docker Image
description: Builds the FusRR Docker Image with latest and commit sha tags

inputs:
  image_name_latest:
    description: "The name of the Docker image with the :latest tag"
    required: true
  image_name_sha:
    description: "The name of the Docker image with the :commit_sha tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        load: true
        tags: ${{ inputs.image_name_latest }}, ${{ inputs.image_name_sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
