name: FusRR - on-push-main-dev

on:
  push:
    branches: [develop, main]

env:
  IMAGE_NAME_W_SHA: fusrr/fusrr:${{ github.sha }}

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python and Hatch
        uses: ./.github/workflows/actions/setup-hatch
      - name: Run Hatch linting tasks
        uses: ./.github/workflows/actions/hatch-lint

  build_image_run_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build FusRR Docker image
        uses: ./.github/workflows/actions/build-docker-image
        with:
          image_tags: ${{ env.IMAGE_NAME_W_SHA }}

      - name: Run tests in Docker
        run: |
          docker run --rm -e FUSRR_RUN_TYPE=tests ${{ env.IMAGE_NAME_W_SHA }}

      - name: Run examples in Docker
        run: |
          docker run --rm -e FUSRR_RUN_TYPE=examples ${{ env.IMAGE_NAME_W_SHA }}

      - name: Push FusRR Docker image
        uses: ./.github/workflows/actions/push-docker-image
        with:
          image_tags: ${{ env.IMAGE_NAME_W_SHA }}
