name: FusRR - On PR

# TODO: Rename the docker image tag to pr-<pr_number>
# upload it and then download it in each job

# or run test -> examples serially

on: [pull_request]

env:
  IMAGE_NAME_W_SHA: fusrr/fusrr:${{ github.sha }}
  IMAGE_NAME_LATEST: fusrr/fusrr:latest

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python and Hatch
        uses: ./.github/actions/setup-hatch
      - name: Run Hatch linting tasks
        uses: ./.github/actions/hatch-lint

  build_image_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build FusRR Docker image
        uses: ./.github/actions/build_docker_image
        with:
          image_name_latest: ${{ env.IMAGE_NAME_W_SHA }}
          image_name_sha: ${{ env.IMAGE_NAME_LATEST }}
      - name: Run tests in Docker
        run: |
          docker run --rm -e FUSRR_RUN_TYPE=tests ${{ env.IMAGE_NAME_W_SHA }}
      - name: Run examples in Docker
        run: |
          docker run --rm -e FUSRR_RUN_TYPE=examples ${{ env.IMAGE_NAME_W_SHA }}
