name: FusRR - publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    # environment: release
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push FusRR Docker image
        uses: ./.github/workflows/actions/push-docker-image-ghcr
        with:
          image_name: "fusrr"
